### ISSUE TITLE
Hash is not deleted with image

### ISSUE THREAD

**Issue by gabe565** [chrisiaut/pictshare#17]
Whenever I delete an image with the master delete code, if I later attempt to upload the same image, I get a broken link.

I would presume this is because it is attempting to link up the old hash, which still shows up in the hashes.csv.

![screenshot 2](https://cloud.githubusercontent.com/assets/7717888/19425564/85ec6b84-93f9-11e6-8273-7b5d3cea6466.jpg)

**Comment by chrisiaut** [comment]
Thx for the report
