### ISSUE TITLE
Upload does not work when master upload code is set

### ISSUE THREAD

**Issue by kirtan007** [chrisiaut/pictshare#18]
1. Set master upload code
2. try to upload image from form
3. it says invalid upload code always.

**Comment by chrisiaut** [comment]
Can't reproduce. Works for me.

What precise upload code did you use?

**Comment by kirtan007** [comment]
problem is in processSingleUpload() 
code is 
` if(UPLOAD_CODE && !$pm->uploadCodeExists($_REQUEST['upload_code']))
`
which should be 
` if(UPLOAD_CODE && !$this->uploadCodeExists($_REQUEST['upload_code']))`

**Comment by chrisiaut** [comment]
thx
