### ISSUE TITLE
Delete image

### ISSUE THREAD

**Issue by soniram** [chrisiaut/pictshare#23]
Hi, and thanks for sharing pictshare !!
Upload is working perfectly but delete has some glitches...
I'm using a post call and although delete works, it returns 404 with this html message 
Warning: unlink(/var/www/vhosts/xxx/xxx.com/upload/delete_temp.csv): No such file or directory in /var/www/vhosts/xxx/xxx.com/models/pictsharemodel.php on line 145.
I have the same behavior even if I send the delete url by hand.
Am I doing something wrong ?

**Comment by chrisiaut** [comment]
thanks :)

The 404 is okay since the image can't be found after being deleted. Might add an error image in the future

**Comment by soniram** [comment]
Thanks for replying !
An end point like backend.php but for delete, that returns a json response might be more elegant and useful.... :-)

**Comment by chrisiaut** [comment]
good idea!
