### ISSUE TITLE
Start a demo with docker, but didn't work

### ISSUE THREAD

**Issue by jacobzeng** [chrisiaut/pictshare#29]
Hi , thanks for the tool.

I want to try a demo, just start it with docker, but i can't upload any image, no error message, and i checked the nginx access.log, it's seem fine.

172.17.0.1 - - [03/May/2017:02:57:48 +0000] "POST / HTTP/1.1" 200 1720 "http://192.168.3.52/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/
537.36"
172.17.0.1 - - [03/May/2017:02:58:11 +0000] "POST / HTTP/1.1" 200 1720 "http://192.168.3.52/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/
537.36"

**Comment by chrisiaut** [comment]
Please repost in the pictshare-docker repo https://github.com/HaschekSolutions/PictShare-Docker
