### ISSUE TITLE
Can't show pictures after uploading

### ISSUE THREAD

**Issue by seuplus** [chrisiaut/pictshare#34]
Sir. I like pictshare very much. But I failed many times when I tried to install it on my VPS (CentOS 7 & LNMP). I can find the picture in `upload` folder after I upload picture `001.jpg` like this
```
- upload
  - 001.jpg
    - 001.jpg
```
But it can't show after finishing uploading. https://img.muzi.moe
Hope to get your helps. Thank you!
![Screen Shot 2017-06-21 at 16.45.40.png](https://ooo.0o0.ooo/2017/06/21/594a325bb74b1.png)

**Comment by chrisiaut** [comment]
do you have the graphicslibrary php-gd installed?

**Comment by seuplus** [comment]
`yum install php-gd`
`Package php-gd-5.4.16-42.el7.x86_64 already installed and latest version`

Yes, Sir. I have had `php-gd`  installed on CentOS and added rewrite rules to nginx conf. But it didn't work. 
```
location / {
     try_files $uri $uri/ /index.php?url=$request_uri; # instead of htaccess mod_rewrite
}
```

I tried to install pictshare in LAMP and it succeed showing pictures after `chmod -R 777 upload`.

PS: 
Nginx: https://img.muzi.moe      Apache: https://im.muzi.moe

**Comment by chrisiaut** [comment]
Okay it seems like you have a problem with your nginx configuration but it seems good to me

**Comment by chrisiaut** [comment]
interestingly it only has a problem with .jpg files since https://img.muzi.moe/xx/xx works but https://img.muzi.moe/xx/xx.jpg doesn't

**Comment by seuplus** [comment]
Thanks for your replies. Sir.
I'm not familiar with Nginx very much. So I'm intended to use pictshare on LAMP for the moment.
