### ISSUE TITLE
Viewer functionality

### ISSUE THREAD

**Issue by yvillazon** [chrisiaut/pictshare#35]
He Chris, great work with pictshare, please if possible (or exists) a viewer for pictshare admin through view all images uploaded ?

**Comment by chrisiaut** [comment]
Not at the moment, no. As a server admin you can always mount the storage folder and look through them yourself.

I once wrote a script that checked all images on pictshare for pornography using the "nsfw detector" on [api heaven](http://www.apiheaven.com/) and I was able to sadly find child pornography and reported it to interpol.

Will maybe implement it to pictshare itself
