### ISSUE TITLE
Valid response back, no image on server

### ISSUE THREAD

**Issue by scorobogaci** [chrisiaut/pictshare#36]
![ui-response](https://user-images.githubusercontent.com/11941776/29278757-5b716df6-811e-11e7-8a22-06c683fbec4a.png)
 Server response is ok
`{"status":"OK","type":"png","hash":"1ucq23hnr5.png","url":"http:\/\/192.168.99.100\/1ucq23hnr5.png","domain":"http:\/\/192.168.99.100"}`

But image is not present in upload folder

**Comment by scorobogaci** [comment]
Accesing after the url : http:\/\/192.168.99.100\/1ucq23hnr5.png
redirects to the default upload page

**Comment by chrisiaut** [comment]
looks like you have permission problems. check if the upload folders are created

**Comment by scorobogaci** [comment]
@chrisiaut , upload folder is created inside container 
/usr/share/nginx/html/upload exists

**Comment by chrisiaut** [comment]
yeah but inside the upload folder is the 1ucq23hnr5.png folder created?

**Comment by scorobogaci** [comment]
@chrisiaut nope, 1ucq23hnr5.png folder isn't  created 
also, sometimes image after upload appears for preview, sometimes not . but when clicking on the image, it redirects to default page

**Comment by chrisiaut** [comment]
must be a permission problem then

**Comment by scorobogaci** [comment]
logs from error.log on the container 

2017/08/14 15:54:21 [error] 229#229: *59 FastCGI sent in stderr: "PHP message: P
HP Notice:  Undefined index: HTTPS in /usr/share/nginx/html/index.php on line 17
" while reading response header from upstream, client: 192.168.99.1, server: _,
request: "POST / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168
.99.100", referrer: "http://192.168.99.100/"
2017/08/14 15:55:12 [error] 231#231: *63 FastCGI sent in stderr: "PHP message: P
HP Notice:  Undefined index: HTTPS in /usr/share/nginx/html/index.php on line 17
" while reading response header from upstream, client: 192.168.99.1, server: _,
request: "POST /17aa3ngtwl.jpg HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000",
host: "192.168.99.100", referrer: "http://192.168.99.100/17aa3ngtwl.jpg"

**Comment by chrisiaut** [comment]
that's just notices, nothing unusual. No seriously check the permissions of the upload folder

**Comment by scorobogaci** [comment]
![permisions](https://user-images.githubusercontent.com/11941776/29280939-c1cf5e1c-8125-11e7-8283-5d0ea0a32c15.png)

**Comment by scorobogaci** [comment]
at permissions level seems to be ok

**Comment by chrisiaut** [comment]
try the command

`sudo su -c "touch /usr/share/nginx/html/upload/check" nginx`

and see if it gets created or if it says permission denied

**Comment by scorobogaci** [comment]
I know it;s kind of strange, but after restarting pc , everything worked 
I've metioned that i have an app on :9000 port , and somehow SGI remember the request from that app, which is using this service, and even that after I'm making request from the app page, it still apend on the log file the old request from :9000

**Comment by scorobogaci** [comment]
`sudo su -c "touch /usr/share/nginx/html/upload/check" nginx`
sudo is not available in container :(

**Comment by scorobogaci** [comment]
@chrisiaut thank you for your help :)
Can you also add cors requests to the app, things like :
`header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET, POST, PUT, DELETE');
header('Access-Control-Allow-Headers: Authorization');`

I don't know it this is a good practice , but maybe you have another idea or good practice to deal with it
