### ISSUE TITLE
Make an option to be API only

### ISSUE THREAD

**Issue by daminufe** [chrisiaut/pictshare#37]
Hello, this is an excellent application, and I am going to start to use it as my private Image hosting API.

I miss the option to hide all the interfaces, and to be API only.
Is there a way to do it? If not, I leave here the suggestion.

**Comment by chrisiaut** [comment]
well you can do it with the ```UPLOAD_FORM_LOCATION``` in the config. you can specify the url where the interface will be shown. if you change that to something nobody will know like "define('UPLOAD_FORM_LOCATION', 'asddasoqeiasjdokasdlkds/asdasdasdasd/');" nobody will ever find it ;D

**Comment by daminufe** [comment]
I didn't thought on that :P Thanks, that's a really good one.

**Comment by daminufe** [comment]
I am using Docker, how do I do it? I tried using an ENV variable `UPLOAD_FORM_LOCATION` and the `UPLOADPATH`, but both didn't work
