### ISSUE TITLE
Self-signed URLs for upload

### ISSUE THREAD

**Issue by daminufe** [chrisiaut/pictshare#38]
Similar to S3, would be nice to be able to get a self-signed URL, so my application could upload directly an image to PictShare without going via backend.

I don't want to expose the secret to upload the images on my frontend application.
So right now to solve that issue, I upload the image to my backend, and then the backend uploads to the pictshare.

My suggestion would be a way to accept uploads from the frontend without having the secret in there.

**Comment by chrisiaut** [comment]
Not quite sure what you mean. You want the ability to upload to pictshare without using pictshare?

**Comment by nelsondspy** [comment]
@daminufe , what is the difference between to use  'UPLOAD_CODE' and the 'self-signed URL'?.  If i have your  'self-signed URL' ,  can i upload images in your server?

**Comment by daminufe** [comment]
@chrisiaut it's exactly like AWS S3 allows to do.
http://docs.aws.amazon.com/AmazonS3/latest/dev/PresignedUrlUploadObject.html

Look at this schema:
![flow](https://user-images.githubusercontent.com/4832774/29869818-dda03d8a-8d84-11e7-9f58-b80b23be7b96.jpg)

In a nutshell, my backend only creates a signed token that is known on the PictShare, to upload directly to it without making the image going to my backend.

**Comment by daminufe** [comment]
@chrisiaut any idea on that?

**Comment by chrisiaut** [comment]
imho not worth it at the moment unless you want to send a pull request
