### ISSUE TITLE
docker-compose.yml has a space in the file name

### ISSUE THREAD

**Issue by evaera** [chrisiaut/pictshare#47]
The file " docker-compose.yml" in this repository has a space in front of it.

The README says to use wget to grab this file for use with Docker, but the snippet in the README doesn't work.

```
wget https://raw.githubusercontent.com/chrisiaut/pictshare/master/docker-compose.yml
```

This is the actual URL of the file: https://raw.githubusercontent.com/chrisiaut/pictshare/master/%20docker-compose.yml

**Comment by chrisiaut** [comment]
fixed in 8146452267360d0b3db21bc5c7a64df4bed56600

**Comment by evaera** [comment]
My PR didn't fix this issue, this is separate. :)

**Comment by chrisiaut** [comment]
oh! then we'll have to ask @yellowsoar as he wrote the docker-compose file

**Comment by chrisiaut** [comment]
oh sorry I get the problem now

**Comment by yellowsoar** [comment]
Ops...Sorry for that typo ><|||
