### ISSUE TITLE
Adding URL upload field to image upload page

### ISSUE THREAD

**Issue by zerokaneda** [chrisiaut/pictshare#69]
I see that it is possible to upload an image via its URL, but it feels a little convoluted and honestly when doing it by hand it's simpler to just download an image and then upload the saved file from your pictshare server front page.

Is there a way to add a form there for uploading remote images without having to manually write it into the application? Just looking for a little place where I paste an image url and hit the Upload button, just like I would hit Browse and upload to upload a locally saved image.

**Comment by chrisiaut** [comment]
Awesome idea
