### ISSUE TITLE
upload image from cordova

### ISSUE THREAD

**Issue by hmdadou** [chrisiaut/pictshare#9]
Hi there thanks for this great piece of work I've uploaded all files working just fine.
I have one question though I've tried to add the url for upload in my hybrid app in view to upload the image via cordova.
you have mentioned in your readme file the following.
UPLOAD_CODE
If set, will show users a code field in the upload form. If it doesn't match your setting, files won't be uploaded.
If enabled, the Upload API will need the variable upload_code via GET (eg: https://pictshare.net/backend.php?getimage=**https://www.0xf.at/css/imgs/logo.png**&upload_code=YourUploadCodeHere)

what if I am uploading the image from my phone there will be no url per se.
in my file I have the path of the image only.
Any help will be much appreciated

**Comment by aVolpe** [comment]
You can post the image as a multipart, add a part with the name `postimage` with your image as a stream, and POST it to `http://HSOT/backend.php`.

Here are a example code for Cordova with [this plugin](https://github.com/apache/cordova-plugin-file-transfer):

```javascript
var uri = encodeURI('http://HSOT/backend.php');
var fileUri = // here the LOCAL uri of your image (the result from the camera or gallery)
var ft = new FileTransfer();
var options = new FileUploadOptions();
options.fileName = 'myPicture';
options.fileKey = 'postimage';
ft.upload(fileUri, uri, function(result) {
    console.log(result);
});
```

**Comment by hmdadou** [comment]
Thanks for your swift response.
I've used your code almost similar to mine I get success callback but nothing has been uploaded I don't know whether the cordova script or the php script.
here's my version still i get upload successful but nothing has been uploaded.
`		function uploadPhoto(imageURI) {
			alert("imageURI: " + imageURI);
			$('#cameraPic').attr('src',imageURI);
			//$("#cameraPic").rotate(90);
	
		
		var options = new FileUploadOptions();
		options.fileKey = "postimage";
		var userid = '123456';
		var imagefilename = userid +'generatedimg' + ".jpg";
		alert(imagefilename);
		options.fileName = imagefilename;
		options.mimeType = "image/jpg";
		var ft = new FileTransfer();
		var url = encodeURI('http://site/pictures/backend.php');
		ft.upload(imageURI, url, win, fail, options, true);
		}`
everything is showing fine in each alert ...

Thanks

**Comment by aVolpe** [comment]
@hmdadou the FileUpload is a mess, please add a console log in `win`, `fail`, and see the server log to see if something happens.

**Comment by hmdadou** [comment]
At last there is a light at the end of the tunnel, the problem I had I've already added upload code as soon as I put it false it worked.
Though I've tried to add the code in here
`options.fileKey = "postimage&upload_code=YourUploadCodeHere";`

didn't work any idea where I could try to add it?

**Comment by aVolpe** [comment]
your `upload_code` must be in your `imageURI` variable, something like this:

```javascript
var finalUrl = imageURI + '&upload_code=' + superSecretCode;
```

**Comment by hmdadou** [comment]
Thanks for the suggestion unfortunately didn't work, I actually tried it i get success from cordova but nothing has been uploaded to the server without the upload code works fine.

**Comment by aVolpe** [comment]
Please add your working code @hmdadou

**Comment by hmdadou** [comment]
I couldn't manage to make it work with the upload code but it is working without it.

**Comment by chrisiaut** [comment]
Note that the upload code is checked in PHP with $_REQUEST, meaning you can use it as GET or as POST variable.
Also note that @aVolpe made a small mistake in his code above (i edited his reply) and it should look like this:

```javascript
finalUrl = encodeURI('http://site/pictures/backend.php?upload_code=' + superSecretCode)
```
